### PR TITLE
Add support for OSX

### PR DESCRIPTION
**Pull request by lbeuster**
This is a precondition to use dbus-java on OSX.

I created the shared lib with the following project: https://github.com/lbeuster/libmatthew-osx.git
Minimum OSX version is 10.6. Compiled for 64 bit.

### CODE REVIEW

**Comment by hypfvieh** [comment]
Thanks for your request.

Before I merge this, we need a way to figure out which native library has to be loaded.

Currently I only check the architecture (e.g. x86_64 or arm), but we need the used OS as well (I assumed that it is always linux, as I don't have or use MacOS).

As far as I know System.getProperty("os.name") gives the OS name, but it might be something like 'darwin' or whatever for MacOS. So we have to figure this out before.

**Comment by lbeuster** [comment]
These are some system properties on MacOS (latest version 10.13 High Sierra)
```
java.vendor=Oracle Corporation
java.version=1.8.0_161
java.specification.vendor=Oracle Corporation
sun.arch.data.model=64
java.vm.specification.version=1.8
java.specification.version=1.8
os.version=10.13.4
os.name=Mac OS X
java.vm.specification.vendor=Oracle Corporation
os.arch=x86_64
java.vm.vendor=Oracle Corporation
```

**Comment by lbeuster** [comment]
It is not necessary (and should not be done) to put the OSX version (10.13) in the path to the shared lib (src/main/resources/macos/10.13/x86_64/libunix-java.so). Instead the lib is compiled for a minimum version=10.6 and works with all newer versions. 10.6 should be old enough but it's still possible to compile for an older version.
Just removing the "10.13" from the path should be a good solution.

**Comment by hypfvieh** [comment]
No I wont remove the version.
In my experience, when assuming something like "nobody uses something older than X", Murphy comes into play..

Just as I always thought that DBus is only used on Linux and not on MacOS (always thought Apple is doing some own (extra) stuff, like always).

Same thing just happened to me when providing a binary version of the lib for raspberry... I used a Raspi 3, compiling for ARMv7... a few weeks later someone was here and complained that he cannot use this on Raspi Zero because it is ARMv6... 

So I added a fix that will take your library for all MacOS versions between 10.6 and 10.13.
I hope that your compiled version will really work with older versions, I have no way to test that.

**Comment by lbeuster** [comment]
Ok, but since this lib works for 10.6+ the directory should be named 10.6.

**Comment by lbeuster** [comment]
Oh, and the current solution doesn't work for 10.14+ (not available yet). The lib should be loaded for all versions greater than 10.6. I don't expected that a newer OSX version doesn't work with an older lib.

**Comment by hypfvieh** [comment]
you don't expect that, but you never know.
Anyways, I will improve the code so newer versions will try the old lib.

**Comment by lbeuster** [comment]
Of course I never know, but at least there's very good chance with the new OSX version. With the limitation to 10.13 there's no chance at all ;)

**Pull request merged**
